CREATE OR REPLACE FUNCTION verifica_texto_movimento_G1G2(id_movimento integer) RETURNS varchar AS $$
declare 

txtMov varchar;
cod_movimento integer;

begin

	cod_movimento := id_movimento;
	txtMov        := '';

	IF    cod_movimento=3 		THEN txtMov='Decisão ou Despacho';
	ELSIF cod_movimento=133 	THEN txtMov='Decisão ou Despacho Acolhimento de exceção';
	ELSIF cod_movimento=335 	THEN txtMov='Acolhida a exceção de pré-executividade';
	ELSIF cod_movimento=940 	THEN txtMov='Acolhida a exceção de Impedimento ou Suspeição';
	ELSIF cod_movimento=371 	THEN txtMov='Acolhida a exceção de Incompetência';
	ELSIF cod_movimento=83 		THEN txtMov='Determinado o cancelamento da distribuição';
	ELSIF cod_movimento=332 	THEN txtMov='Concedida a Antecipação de tutela';
	ELSIF cod_movimento=787 	THEN txtMov='Concedida a Assistência Judiciária Gratuita';
	ELSIF cod_movimento=339 	THEN txtMov='Concedida a Medida Liminar';
	ELSIF cod_movimento=12308 	THEN txtMov='Concedida a substituição/sucessão de parte';
	ELSIF cod_movimento=888 	THEN txtMov='Decisão ou Despacho Concessão em parte';
	ELSIF cod_movimento=889 	THEN txtMov='Concedida em parte a Antecipação de Tutela';
	ELSIF cod_movimento=892 	THEN txtMov='Concedida em parte a Medida Liminar';
	ELSIF cod_movimento=7 		THEN txtMov='Convertido(a) o(a)';
	ELSIF cod_movimento=266 	THEN txtMov='Convertido(a) o(a) Julgamento em Diligência';
	ELSIF cod_movimento=12387 	THEN txtMov='Decisão de Saneamento e de Organização do Processo';
	ELSIF cod_movimento=12185 	THEN txtMov='Decisão Interlocutória de Mérito';
	ELSIF cod_movimento=11 		THEN txtMov='Decisão ou Despacho Declaração';
	ELSIF cod_movimento=12150 	THEN txtMov='Declarado impedimento pelo magistrado';
	ELSIF cod_movimento=269 	THEN txtMov='Declarado impedimento ou suspeição';
	ELSIF cod_movimento=941 	THEN txtMov='Declarada incompetência';
	ELSIF cod_movimento=12151 	THEN txtMov='Declarada suspeição pelo magistrado';
	ELSIF cod_movimento=113 	THEN txtMov='Decisão ou Despacho Decretação de Prisão Civil';
	ELSIF cod_movimento=355 	THEN txtMov='Decretada a prisão de depositário infiel';
	ELSIF cod_movimento=12307 	THEN txtMov='Decretada a revelia';
	ELSIF cod_movimento=12444 	THEN txtMov='Deferido o pedido de';
	ELSIF cod_movimento=1013 	THEN txtMov='Decisão Determinação';
	ELSIF cod_movimento=11382 	THEN txtMov='Determinado o bloqueio/penhora on line';
	ELSIF cod_movimento=12457 	THEN txtMov='Determinada expedição de Precatório/RPV';
	ELSIF cod_movimento=12040 	THEN txtMov='Decretada a indisponibilidade de bens';
	ELSIF cod_movimento=12037 	THEN txtMov='Determinada a quebra do sigilo fiscal';
	ELSIF cod_movimento=12255 	THEN txtMov='Determinação de redistribuição por prevenção';
	ELSIF cod_movimento=378 	THEN txtMov='Decisão ou Despacho Homologação';
	ELSIF cod_movimento=377 	THEN txtMov='Homologado Acordo em execução ou em cumprimento de sentença';
	ELSIF cod_movimento=944 	THEN txtMov='Homologada a Desistência do Recurso';
	ELSIF cod_movimento=968 	THEN txtMov='Decisão ou Despacho Não-Concessão';
	ELSIF cod_movimento=785 	THEN txtMov='Não Concedida a Antecipação de tutela';
	ELSIF cod_movimento=334 	THEN txtMov='Assistência Judiciária Gratuita não concedida';
	ELSIF cod_movimento=792 	THEN txtMov='Não Concedida a Medida Liminar';
	ELSIF cod_movimento=163 	THEN txtMov='Decisão ou Despacho Não-Recebimento';
	ELSIF cod_movimento=804 	THEN txtMov='Não recebido o recurso';
	ELSIF cod_movimento=12300 	THEN txtMov='Nomeado(a)';
	ELSIF cod_movimento=12301 	THEN txtMov='Nomeado advogado voluntário';
	ELSIF cod_movimento=12302 	THEN txtMov='Nomeado curador';
	ELSIF cod_movimento=12303 	THEN txtMov='Nomeado defensor dativo';
	ELSIF cod_movimento=12304 	THEN txtMov='Nomeado intérprete/tradutor';
	ELSIF cod_movimento=12305 	THEN txtMov='Nomeado outro auxiliar da justiça';
	ELSIF cod_movimento=12306 	THEN txtMov='Nomeado perito';
	ELSIF cod_movimento=63 		THEN txtMov='Ordenada a entrega dos autos à parte';
	ELSIF cod_movimento=160 	THEN txtMov='Decisão ou Despacho Recebimento';
	ELSIF cod_movimento=12261 	THEN txtMov='Recebida a emenda à inicial';
	ELSIF cod_movimento=190 	THEN txtMov='Reformada decisão anterior';
	ELSIF cod_movimento=138 	THEN txtMov='Decisão ou Despacho Rejeição';
	ELSIF cod_movimento=374 	THEN txtMov='Rejeitada a exceção de incompetência';
	ELSIF cod_movimento=788 	THEN txtMov='Rejeitada a exceção de pré-executividade';
	ELSIF cod_movimento=56 		THEN txtMov='Decisão Requisita Informações';
	ELSIF cod_movimento=157 	THEN txtMov='Decisão ou Despacho Revogação';
	ELSIF cod_movimento=347 	THEN txtMov='Revogada a Antecipação de Tutela Jurisdicional';
	ELSIF cod_movimento=945 	THEN txtMov='Revogada decisão anterior';
	ELSIF cod_movimento=348 	THEN txtMov='Revogada a Medida Liminar';
	ELSIF cod_movimento=128 	THEN txtMov='Revogada a Prisão';
	ELSIF cod_movimento=961 	THEN txtMov='Suscitado Conflito de Competência';
	ELSIF cod_movimento=25 		THEN txtMov='Processo Suspenso ou Sobrestado por';
	ELSIF cod_movimento=272 	THEN txtMov='Processo Suspenso por depender do julgamento de outra causa, de outro juízo ou declaração incidente';
	ELSIF cod_movimento=960 	THEN txtMov='Processo Suspenso ou Sobrestado por Conflito de Competência';
	ELSIF cod_movimento=270 	THEN txtMov='Processo Suspenso por Convenção das Partes';
	ELSIF cod_movimento=277 	THEN txtMov='Processo Suspenso ou Sobrestado por Convenção das Partes para Cumprimento Voluntário da obrigação';
	ELSIF cod_movimento=271 	THEN txtMov='Processo Suspenso por Exceção de Incompetência, suspeição ou Impedimento';
	ELSIF cod_movimento=276 	THEN txtMov='Processo Suspenso por Execução Frustrada';
	ELSIF cod_movimento=275 	THEN txtMov='Processo Suspenso ou Sobrestado por Força maior';
	ELSIF cod_movimento=12098 	THEN txtMov='Processo Suspenso por Incidente de Resolução de Demandas Repetitivas';
	ELSIF cod_movimento=268 	THEN txtMov='Processo Suspenso por Morte ou perda da capacidade';
	ELSIF cod_movimento=12100 	THEN txtMov='Suspensão por Decisão do Presidente do STF - IRDR';
	ELSIF cod_movimento=12099 	THEN txtMov='Suspensão por Decisão do STJ - IRDR';
	ELSIF cod_movimento=898 	THEN txtMov='Processo Suspenso ou Sobrestado por Por decisão judicial';
	ELSIF cod_movimento=12259 	THEN txtMov='Determinação de suspensão ou sobrestamento dos autos em razão de prescrição intercorrente';
	ELSIF cod_movimento=11024 	THEN txtMov='Concedida a Assistência Judiciária Gratuita a parte';
	ELSIF cod_movimento=11022 	THEN txtMov='Convertido(a) o(a) Julgamento em Diligência';
	ELSIF cod_movimento=11010 	THEN txtMov='Proferido despacho de mero expediente';
	ELSIF cod_movimento=11019 	THEN txtMov='Ordenada a entrega dos autos à parte';
	ELSIF cod_movimento=11020 	THEN txtMov='Determinada Requisição de Informações';
	ELSIF cod_movimento=11012 	THEN txtMov='Processo Suspenso ou Sobrestado por Conflito de Competência';
	ELSIF cod_movimento=11013 	THEN txtMov='Processo Suspenso por Convenção das Partes';
	ELSIF cod_movimento=11014 	THEN txtMov='Processo Suspenso ou Sobrestado por Convenção das Partes para Cumprimento Voluntário da obrigação';
	ELSIF cod_movimento=11015 	THEN txtMov='Processo Suspenso por Exceção de Incompetência, suspeição ou Impedimento';
	ELSIF cod_movimento=193 	THEN txtMov='Julgamento';
	ELSIF cod_movimento=198 	THEN txtMov='Embargos de Declaração Acolhidos';
	ELSIF cod_movimento=871 	THEN txtMov='Embargos de Declaração Acolhidos em Parte';
	ELSIF cod_movimento=210 	THEN txtMov='Concedido(a)';
	ELSIF cod_movimento=12475 	THEN txtMov='Não conhecido o Habeas Corpus. Concedido o Habeas Corpus de ofício para parte';
	ELSIF cod_movimento=444 	THEN txtMov='Concedido o Habeas Data';
	ELSIF cod_movimento=442 	THEN txtMov='Concedida a Segurança';
	ELSIF cod_movimento=214 	THEN txtMov='Concedido(a) em parte';
	ELSIF cod_movimento=452 	THEN txtMov='Concedido em parte o Habeas Data';
	ELSIF cod_movimento=450 	THEN txtMov='Concedida em parte a Segurança';
	ELSIF cod_movimento=900 	THEN txtMov='Julgado o conflito de competência';
	ELSIF cod_movimento=212 	THEN txtMov='Denegado(a)';
	ELSIF cod_movimento=448 	THEN txtMov='Denegado o Habeas Data';
	ELSIF cod_movimento=446 	THEN txtMov='Denegada a Segurança';
	ELSIF cod_movimento=196 	THEN txtMov='Extinta a execução ou o cumprimento da sentença';
	ELSIF cod_movimento=466 	THEN txtMov='Homologada a Transação';
	ELSIF cod_movimento=220 	THEN txtMov='Julgado improcedente o pedido';
	ELSIF cod_movimento=200 	THEN txtMov='Embargos de Declaração Não-acolhidos';
	ELSIF cod_movimento=219 	THEN txtMov='Julgado procedente o pedido';
	ELSIF cod_movimento=11795 	THEN txtMov='Julgado procedente o pedido - reconhecimento pelo réu';
	ELSIF cod_movimento=221 	THEN txtMov='Julgado procedente em parte do pedido';
	ELSIF cod_movimento=471 	THEN txtMov='Declarada decadência ou prescrição';
	ELSIF cod_movimento=455 	THEN txtMov='Homologada renúncia pelo autor';
	ELSIF cod_movimento=11373 	THEN txtMov='Anulada a(o) sentença/acórdão';
	ELSIF cod_movimento=228 	THEN txtMov='Arquivamento';
	ELSIF cod_movimento=473 	THEN txtMov='Arquivamento Ausência do Reclamante';
	ELSIF cod_movimento=472 	THEN txtMov='Arquivamento Sumaríssimo (art. 852-B, § 1º/CLT)';
	ELSIF cod_movimento=456 	THEN txtMov='Extinto o processo sem resolução do mérito por';
	ELSIF cod_movimento=458 	THEN txtMov='Extinto o processo por abandono da causa pelo autor';
	ELSIF cod_movimento=464 	THEN txtMov='Extinto o processo por ser a ação intransmissível';
	ELSIF cod_movimento=461 	THEN txtMov='Extinto o processo por ausência das condições da ação';
	ELSIF cod_movimento=459 	THEN txtMov='Extinto o processo por ausência de pressupostos processuais';
	ELSIF cod_movimento=465 	THEN txtMov='Extinto o processo por confusão entre autor e réu';
	ELSIF cod_movimento=12256 	THEN txtMov='Extinto o processo sem resolução de mérito por continência';
	ELSIF cod_movimento=462 	THEN txtMov='Extinto o processo por convenção de arbitragem';
	ELSIF cod_movimento=463 	THEN txtMov='Extinto o processo por desistência';
	ELSIF cod_movimento=454 	THEN txtMov='Indeferida a petição inicial';
	ELSIF cod_movimento=457 	THEN txtMov='Extinto o processo por negligência das partes';
	ELSIF cod_movimento=460 	THEN txtMov='Extinto o processo por Perempção, litispendência ou coisa julgada';
	ELSIF cod_movimento=235 	THEN txtMov='Não conhecido o recurso';
	ELSIF cod_movimento=12458 	THEN txtMov='Não conhecido o Habeas Corpus';
	ELSIF cod_movimento=870 	THEN txtMov='Autos Eliminados';
	ELSIF cod_movimento=869 	THEN txtMov='Entrega Definitiva dos Autos';
	ELSIF cod_movimento=866 	THEN txtMov='Arquivo em Guarda Intermediária';
	ELSIF cod_movimento=867 	THEN txtMov='Arquivo em Guarda permanente';
	ELSIF cod_movimento=977 	THEN txtMov='Recebimento pelo Arquivo';
	ELSIF cod_movimento=978 	THEN txtMov='Remessa do Arquivo';
	ELSIF cod_movimento=12531 	THEN txtMov='Conciliação frutífera';
	ELSIF cod_movimento=12532 	THEN txtMov='Conciliação infrutífera';
	ELSIF cod_movimento=16 		THEN txtMov='realizado cálculo de';
	ELSIF cod_movimento=480 	THEN txtMov='Conta Atualizada';
	ELSIF cod_movimento=478 	THEN txtMov='Realizado Cálculo de Liquidação';
	ELSIF cod_movimento=479 	THEN txtMov='Realizado cálculo de custas';
	ELSIF cod_movimento=481 	THEN txtMov='Realizado Cálculo de Tributos';
	ELSIF cod_movimento=979 	THEN txtMov='Recebidos os Autos pela Contadoria';
	ELSIF cod_movimento=980 	THEN txtMov='Remetidos os autos da Contadoria';
	ELSIF cod_movimento=12297 	THEN txtMov='Atribuição de competência temporária';
	ELSIF cod_movimento=22 		THEN txtMov='Baixa Definitiva';
	ELSIF cod_movimento=488 	THEN txtMov='Cancelada a Distribuição';
	ELSIF cod_movimento=26 		THEN txtMov='Distribuído';
	ELSIF cod_movimento=981 	THEN txtMov='Recebido pelo Distribuidor';
	ELSIF cod_movimento=36 		THEN txtMov='Redistribuído';
	ELSIF cod_movimento=12296 	THEN txtMov='Registrado';
	ELSIF cod_movimento=982 	THEN txtMov='Remetidos os Autos';
	ELSIF cod_movimento=135 	THEN txtMov='Apensado ao processo';
	ELSIF cod_movimento=861 	THEN txtMov='Processo Arquivado';
	ELSIF cod_movimento=246 	THEN txtMov='Arquivado Definitivamente';
	ELSIF cod_movimento=245 	THEN txtMov='Arquivado Provisoramente';
	ELSIF cod_movimento=12293 	THEN txtMov='Ato cumprido pela parte ou interessado';
	ELSIF cod_movimento=12295 	THEN txtMov='Ato cumprido pela parte ou interessado - depósito de bens/dinheiro';
	ELSIF cod_movimento=11383 	THEN txtMov='Ato ordinatório praticado';
	ELSIF cod_movimento=970 	THEN txtMov='Audiência';
	ELSIF cod_movimento=12260 	THEN txtMov='Autos restaurados';
	ELSIF cod_movimento=12289 	THEN txtMov='Cancelamento';
	ELSIF cod_movimento=12290 	THEN txtMov='Cancelado o documento';
	ELSIF cod_movimento=12291 	THEN txtMov='Cancelada a movimentação processual';
	ELSIF cod_movimento=12186 	THEN txtMov='Cancelada a Distribuição';
	ELSIF cod_movimento=12284 	THEN txtMov='Citação';
	ELSIF cod_movimento=12286 	THEN txtMov='Citação eletrônica';
	ELSIF cod_movimento=12288 	THEN txtMov='Confirmada a citação eletrônica';
	ELSIF cod_movimento=12287 	THEN txtMov='Expedida/certificada a citação eletrônica';
	ELSIF cod_movimento=12285 	THEN txtMov='Citado em Secretaria/Comparecimento Espontâneo';
	ELSIF cod_movimento=12281 	THEN txtMov='Cominicação eletrônica';
	ELSIF cod_movimento=12283 	THEN txtMov='Confirmada a comunicação eletrônica';
	ELSIF cod_movimento=12282 	THEN txtMov='Expedida/certificada a comunicação eletrôinica';
	ELSIF cod_movimento=51 		THEN txtMov='Conclusos';
	ELSIF cod_movimento=1051 	THEN txtMov='Decorrido prazo';
	ELSIF cod_movimento=12198 	THEN txtMov='Deliberado em Sessão';
	ELSIF cod_movimento=12199 	THEN txtMov='Deliberado em Sessão - Julgado';
	ELSIF cod_movimento=12202 	THEN txtMov='Deliberado em Sessão - Julgado - Questão de Ordem';
	ELSIF cod_movimento=137 	THEN txtMov='Desapensado do processo';
	ELSIF cod_movimento=893 	THEN txtMov='Processo Desarquivado';
	ELSIF cod_movimento=12269 	THEN txtMov='Desentranhamento';
	ELSIF cod_movimento=12270 	THEN txtMov='Desentranhado o documento';
	ELSIF cod_movimento=12271 	THEN txtMov='Desentranhada a petição';
	ELSIF cod_movimento=11008 	THEN txtMov='Desmembrado o feito';
	ELSIF cod_movimento=1061 	THEN txtMov='Disponibilizado no DJ Eletrônico';
	ELSIF cod_movimento=493 	THEN txtMov='Autos entregues em carga';
	ELSIF cod_movimento=11385 	THEN txtMov='Execução Iniciada';
	ELSIF cod_movimento=60 		THEN txtMov='Expedição';
	ELSIF cod_movimento=12263 	THEN txtMov='Intimação';
	ELSIF cod_movimento=12264 	THEN txtMov='Intimação eletrônica';
	ELSIF cod_movimento=12266 	THEN txtMov='Confirmada a intimação eletrônica';
	ELSIF cod_movimento=12265 	THEN txtMov='Expedida/certificada a intimação eletrônica';
	ELSIF cod_movimento=12267 	THEN txtMov='Intimado em audiência';
	ELSIF cod_movimento=12268 	THEN txtMov='Intimado em Secretaria';
	ELSIF cod_movimento=67 		THEN txtMov='juntada de';
	ELSIF cod_movimento=581 	THEN txtMov='Juntada de Documento';
	ELSIF cod_movimento=85 		THEN txtMov='Juntada de Petição';
	ELSIF cod_movimento=311 	THEN txtMov='Leilão ou Praça';
	ELSIF cod_movimento=11384 	THEN txtMov='Iniciada a liquidação';
	ELSIF cod_movimento=12143 	THEN txtMov='Alterado o assunto processual';
	ELSIF cod_movimento=10966 	THEN txtMov='Classe Processual';
	ELSIF cod_movimento=12142 	THEN txtMov='Alterada a parte';
	ELSIF cod_movimento=12103 	THEN txtMov='Pauta';
	ELSIF cod_movimento=12106 	THEN txtMov='Adiamento do Julgamento (Art. 935 do CPC)';
	ELSIF cod_movimento=12104 	THEN txtMov='Inclusão em Pauta';
	ELSIF cod_movimento=12115 	THEN txtMov='Inclusão em pauta para julgamento de mérito';
	ELSIF cod_movimento=12309 	THEN txtMov='Retirada de pauta';
	ELSIF cod_movimento=118 	THEN txtMov='Protocolizada Petição';
	ELSIF cod_movimento=92 		THEN txtMov='Publicado Ato';
	ELSIF cod_movimento=132 	THEN txtMov='Recebidos os autos';
	ELSIF cod_movimento=12621 	THEN txtMov='Recebidos os autos.';
	ELSIF cod_movimento=123 	THEN txtMov='Remetidos os Autos';
	ELSIF cod_movimento=12622 	THEN txtMov='Remetido para Câmara de Conciliação/Mediação';
	ELSIF cod_movimento=12614 	THEN txtMov='Remetidos os Autos ao CEJUSC';
	ELSIF cod_movimento=928 	THEN txtMov='Republicado Ato';
	ELSIF cod_movimento=848 	THEN txtMov='Transitado em Julgado';
	ELSIF cod_movimento=105 	THEN txtMov='devolvido o';
	ELSIF cod_movimento=106 	THEN txtMov='Mandado devolvido';
	ELSIF cod_movimento=112 	THEN txtMov='Ofício Devolvido';
	ELSIF cod_movimento=115 	THEN txtMov='recebido o mandado';
	ELSIF cod_movimento=985 	THEN txtMov='Recebido o Mandado para Cumprimento';
	ELSIF cod_movimento=987 	THEN txtMov='Recebido o Ofício para Entrega';
	END IF;

	RETURN txtMov;

END
$$ language plpgsql;