CREATE OR REPLACE FUNCTION verificaComplementoTabelado_G1G2(cd_tabelado integer) RETURNS varchar AS $$
declare 

codComplemento		integer;

begin

codComplemento		:= cd_tabelado;

		IF    codComplemento = '1084' THEN
		  codComplemento := '37';  -- EM DILIGÊNCIA
		ELSIF codComplemento = '7000' THEN
		  codComplemento := '117'; -- ACÓRDÃO
		ELSIF codComplemento = '7001' THEN
		  codComplemento := '181'; -- DECISÃO
		ELSIF codComplemento = '7003' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7004' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7006' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7007' THEN
		  codComplemento := '118'; -- SENTENÇA
		ELSIF codComplemento = '7067' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7070' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO		  
		ELSIF codComplemento = '7071' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7073' THEN
		  codComplemento := '30';  -- IMPEDIMENTO
		ELSIF codComplemento = '7077' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7078' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7079' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7080' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO  -- 7
		ELSIF codComplemento = '7081' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7082' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7083' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7084' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO  -- 7
		ELSIF codComplemento = '7085' THEN
		  codComplemento := '37';  -- EM DILIGÊNCIA
		ELSIF codComplemento = '7086' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7087' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7088' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7089' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7090' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7091' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7092' THEN
		  codComplemento := '37';  -- EM DILIGÊNCIA
		ELSIF codComplemento = '7093' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7094' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7095' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7096' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7097' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7098' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7099' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7100' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7101' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7102' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7103' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7104' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7105' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7106' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7107' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
--		ELSIF codComplemento = '7108' THEN
--		  codComplemento := '90';  -- por ter sido acolhida a exceção de incompetência
		ELSIF codComplemento = '7108' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO		  
		ELSIF codComplemento = '7109' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
--		ELSIF codComplemento = '7110' THEN
--		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7110' THEN
		  codComplemento := '108';  -- por ter sido cumprida a diligência		  
		ELSIF codComplemento = '7111' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7112' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7121' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7133' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7141' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7142' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7143' THEN
		  codComplemento := '180';
		ELSIF codComplemento = '7144' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7145' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7146' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7147' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7148' THEN
		  codComplemento := '41';
		ELSIF codComplemento = '7149' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7150' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7151' THEN
		  codComplemento := '164';
		ELSIF codComplemento = '7152' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7153' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7154' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7155' THEN
		  codComplemento := '41';
		ELSIF codComplemento = '7156' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7157' THEN
		  codComplemento := '50';
		ELSIF codComplemento = '7158' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7159' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7174' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7179' THEN
		  codComplemento := '7'; -- ENTREGUE AO DESTINATÁRIO
		ELSIF codComplemento = '7180' THEN
		  codComplemento := '7'; -- ENTREGUE AO DESTINATÁRIO
		ELSIF codComplemento = '7182' THEN
		  codComplemento := '8'; -- NÃO ENTREGUE AO DESTINATÁRIO
		ELSIF codComplemento = '7195' THEN
		  codComplemento := '21'; -- INICIAL
		ELSIF codComplemento = '7198' THEN
		  codComplemento := '97'; -- ADIADO O JULGAMENTO'
		ELSIF codComplemento = '7199' THEN
		  codComplemento := '98'; -- CONVERTIDO EM DILIGÊNCIA
		ELSIF codComplemento = '7200' THEN
		  codComplemento := '99'; -- PEDIDO DE VISTAS
		ELSIF codComplemento = '7201' THEN
		  codComplementoTabelado := '100'; -- RETIFICAÇÃO DO RESULTADO DE JULGAMENTO
		ELSIF codComplemento = '7202' THEN
		  codComplemento := '101'; -- RETIRADO DE PAUTA		  
		ELSIF codComplemento = '7206' THEN --OK
		  codComplemento := '1'; -- COMPETENCIA EXCLUSIVA
		ELSIF codComplemento = '7207' THEN --OK
		  codComplemento := '4'; -- DEPENDÊNCIA
		ELSIF codComplemento = '7208' THEN --OK
		  codComplemento := '3'; -- PREVENÇÃO
		ELSIF codComplemento = '7209'  THEN --OK
		  codComplemento := '2'; -- SORTEIO
		ELSIF codComplemento = '7210' THEN --OK
		  codComplemento := '85'; -- SORTEIO MANUAL
		ELSIF codComplemento = '7211' THEN --OK
		  codComplemento := '4'; -- DEPENDÊNCIA
		ELSIF codComplemento = '7212' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7213' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7214' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7215' THEN
		  codComplemento := '77';  -- CARTA ROGATÓRIA
		ELSIF codComplemento = '7216' THEN
		  codComplemento := '77';  -- CARTA ROGATÓRIA
		ELSIF codComplemento = '7217' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7218' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7219' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7220' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7221' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS		  
		ELSIF codComplemento = '7223' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7222' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7224' THEN
		  codComplemento := '79';  -- OFÍCIO
		ELSIF codComplemento = '7225' THEN
		  codComplemento := '79';  -- OFÍCIO
		ELSIF codComplemento = '7226' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7227' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7228' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7229' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7230' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7231' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7247' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7248' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
--		ELSIF codComplemento = '7249' THEN
--		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7249' THEN
		  codComplemento := '46';
		ELSIF codComplemento = '7250' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7251' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7252' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7253' THEN
		  codComplemento := '3'; -- PREVENÇÃO
		ELSIF codComplemento = '7254' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7255' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7259' THEN
		  codComplemento := '40';  -- OUTROS MOTIVOS
		ELSIF codComplemento = '7262' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7263' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7278' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7279' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7295' THEN
		  codComplemento := '117'; -- ACÓRDÃO
		ELSIF codComplemento = '7296' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7297' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7298' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7299' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7300' THEN
		  codComplemento := '182'; -- ATO COATOR
		ELSIF codComplemento = '7301' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7302' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7303' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7304' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7305' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7306' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7307' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7308' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7309' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7310' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7311' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7312' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7313' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7314' THEN
		  codComplemento := '77';  -- CARTA ROGATÓRIA
		ELSIF codComplemento = '7315' THEN
		  codComplemento := '77';  -- CARTA ROGATÓRIA
		ELSIF codComplemento = '7316' THEN
		  codComplemento := '77';  -- CARTA ROGATÓRIA
		ELSIF codComplemento = '7317' THEN
		  codComplemento := '77';  -- CARTA ROGATÓRIA
		ELSIF codComplemento = '7318' THEN
		  codComplemento := '77';  -- CARTA ROGATÓRIA
		ELSIF codComplemento = '7319' THEN
		  codComplemento := '77';  -- CARTA ROGATÓRIA
		ELSIF codComplemento = '7320' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7321' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7322' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7332' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7333' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7334' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7335' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7336' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7323' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7324' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7325' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7326' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7327' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7328' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7329' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7330' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7331' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7337' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7338' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7339' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7340' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7340' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7341' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7342' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7343' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7344' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7345' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7346' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7347' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7348' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7349' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7350' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7351' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7352' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7353' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7354' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7355' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7356' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7357' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7358' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7359' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7360' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7361' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7362' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7363' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7364' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7365' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7366' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7367' THEN
		  codComplemento := '116'; -- INFORMAÇÕES
		ELSIF codComplemento = '7368' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7369' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7370' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7371' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7372' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7373' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7374' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7375' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7376' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7377' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7378' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7379' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7380' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7381' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7382' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7383' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7384' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7385' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7386' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7387' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7388' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS		  
		ELSIF codComplemento = '7389' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7390' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7391' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7392' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7393' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7394' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7395' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7396' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7397' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7398' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7399' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7400' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7401' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7402' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7403' THEN
		  codComplemento := '118'; -- SENTENÇA
		ELSIF codComplemento = '7404' THEN
		  codComplemento := '118'; -- SENTENÇA
		ELSIF codComplemento = '7405' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7406' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7407' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7408' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7409' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7410' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7411' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7412' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7413' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7414' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7415' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7416' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7417' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7418' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7419' THEN
		  codComplemento := '112';
		ELSIF codComplemento = '7420' THEN
		  codComplemento := '55';
		ELSIF codComplemento = '7421' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7422' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7423' THEN
		  codComplemento := '111';
		ELSIF codComplemento = '7424' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7425' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7426' THEN
		  codComplemento := '112';
		ELSIF codComplemento = '7427' THEN
		  codComplemento := '113';
		ELSIF codComplemento = '7428' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7430' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7431' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7432' THEN
		  codComplemento := '45';
		ELSIF codComplemento = '7433' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7434' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7435' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7436' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7437' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7438' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7439' THEN
		  codComplemento := '115';
		ELSIF codComplemento = '7440' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7441' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7442' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7443' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7444' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7445' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7448' THEN
		  codComplemento := '117'; -- ACÓRDÃO
		ELSIF codComplemento = '7449' THEN
		  codComplemento := '117'; -- ACÓRDÃO
		ELSIF codComplemento = '7450' THEN
		  codComplemento := '21'; -- INICIAL
		ELSIF codComplemento = '7451' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7452' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7455' THEN
		  codComplemento := '101'; -- RETIRADO DE PAUTA
		ELSIF codComplemento = '7456' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7457' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7458' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7459' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7460' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7461' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7467' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7477' THEN
		  codComplemento := '21'; -- INICIAL
		ELSIF codComplemento = '7494' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7500' THEN
		  codComplemento := '117';  -- ACÓRDÃO
		ELSIF codComplemento = '7510' THEN
		  codComplemento := '54';
		ELSIF codComplemento = '7511' THEN
		  codComplemento := '117'; -- ACÓRDÃO
		ELSIF codComplemento = '7512' THEN
		  codComplemento := '117'; -- ACÓRDÃO
		ELSIF codComplemento = '7513' THEN
		  codComplemento := '117'; -- ACÓRDÃO
		ELSIF codComplemento = '7514' THEN
		  codComplemento := '117'; -- ACÓRDÃO
		ELSIF codComplemento = '7515' THEN
		  codComplemento := '117'; -- ACÓRDÃO
		ELSIF codComplemento = '7522' THEN
		  codComplemento := '22'; -- INSTRUÇÃO
		ELSIF codComplemento = '7523' THEN
		  codComplemento := '18'; -- DE INTERROGATÓRIO
		ELSIF codComplemento = '7524' THEN
		  codComplemento := '92'; -- MEDIAÇÃO
		ELSIF codComplemento = '7525' THEN
		  codComplemento := '92'; -- MEDIAÇÃO
		ELSIF codComplemento = '7526' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7527' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7528' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7529' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7530' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7531' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7532' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7533' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7534' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7535' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7536' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7537' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7538' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7539' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7540' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7541' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7542' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7543' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7544' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7545' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7546' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7547' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7548' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7549' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7550' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7551' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7552' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7553' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7554' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7555' THEN
		  codComplemento := '48';  -- EMBARGOS A AÇÃO MONITÓRIA
		ELSIF codComplemento = '7556' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7557' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7558' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)		  
		ELSIF codComplemento = '7559' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7560' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7561' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7562' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7563' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7564' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7565' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7566' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7567' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7568' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7569' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7570' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7584' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7585' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7588' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7591' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7629' THEN --OK
		  codComplemento := '4'; -- DEPENDÊNCIA
		ELSIF codComplemento = '7630' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7631' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7632' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7633' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7636' THEN
		  codComplemento := '78'; -- MANDADO
		ELSIF codComplemento = '7649' THEN
		  codComplemento := '107'; -- CERTIDÃO
		ELSIF codComplemento = '7650' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7653' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7671' THEN
		  codComplemento := '117'; -- ACÓRDÃO
		ELSIF codComplemento = '7672' THEN
		  codComplemento := '181'; -- DECISÃO
		ELSIF codComplemento = '7673' THEN
		  codComplemento := '181'; -- DECISÃO
		ELSIF codComplemento = '7674' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7675' THEN
		  codComplemento := '80'; -- OUTROS DOCUMENTOS
		ELSIF codComplemento = '7637' THEN
		  codComplemento := '57'; -- PETIÇÃO (OUTRAS)
		ELSIF codComplemento = '7690' THEN
		  codComplemento := '38';  -- PARA PROCESSAR RECURSO
		ELSIF codComplemento = '7692' THEN
		  codComplemento := '17'; -- CONCILIAÇÃO
		ELSIF codComplemento = '7693' THEN
		  codComplemento := '20'; -- EM EXECUÇÃO
		ELSIF codComplemento = '7694' THEN
		  codComplemento := '22'; -- INSTRUÇÃO
		ELSIF codComplemento = '7695' THEN
		  codComplemento := '18'; -- DE INTERROGATÓRIO
		ELSIF codComplemento = '7696' THEN
		  codComplemento := '22'; -- INSTRUÇÃO
		ELSIF codComplemento = '7698' THEN
		  codComplemento := '92'; -- MEDIAÇÃO
		ELSIF codComplemento = '7699' THEN
		  codComplemento := '21'; -- INICIAL
		ELSIF codComplemento = '7700' THEN
		  codComplemento := '21'; -- INICIAL
		ELSIF codComplemento = '7701' THEN
		  codComplemento := '21'; -- INICIAL
		ELSIF codComplemento = '7702' THEN
		  codComplemento := '21'; -- INICIAL
		ELSIF codComplemento = '7703' THEN
		  codComplemento := '21'; -- INICIAL
	END IF;

	RETURN codComplemento;

END
$$ language plpgsql;